# Generated by Django 5.2.3 on 2025-06-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='visiting_time',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
